# Brings up a pihole container and a dnscrypt-proxy container. 
# The pi-hole container uses dnscrupt as its one and only upstream forwarding server.

services:
  pihole:
    # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "1053:53/tcp"
      - "1053:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "8443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    networks:
      - pihole
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'UTC'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'changeme'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: dnscrypt

    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './pihole-etc:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
      #cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      #- SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      #- SYS_NICE
    restart: unless-stopped

  dnscrypt:
    container_name: dnscrypt
    image: klutchell/dnscrypt-proxy:latest
    networks:
      - pihole
    expose:
      - "53/udp"
      - "53/tcp"
    volumes:
      - './dnscrypt-config:/config'
    restart: unless-stopped

networks:
  pihole:
     external: true
     name: pihole-stubby_pihole

      #networks:
      #  pihole:
      #    driver: bridge
      #    ipam:
      #      config:
      #        - subnet: 172.28.0.0/16
      #          gateway: 172.28.0.1
      #    driver_opts:
      #      com.docker.network.bridge.name: "pihole"
      #      com.docker.network.enable_icc: "true"


